version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_new_password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: your_new_password
      DB_NAME: testdb
#docker exec -it backend_db_1 mysql -u root -p